In [16]:
# ============================================================
# QUANTUM STATES: KETS, BRAS, OPERATORS & DENSITY MATRICES (Linear Algebra)
# ============================================================

import numpy as np
from numpy import linalg as LA

np.set_printoptions(precision=3, suppress=True)

In [17]:
# Define computational basis states (Kets and Bras)

ket0 = np.array([[1],
                 [0]])

ket1 = np.array([[0],
                 [1]])

print("Ket |0>:\n", ket0)
print("\nKet |1>:\n", ket1)

# Bra is conjugate transpose
bra0 = ket0.conj().T
bra1 = ket1.conj().T
print("\nBra <0|:\n", bra0)
print("\nBra <1|:\n", bra1)

Ket |0>:
 [[1]
 [0]]

Ket |1>:
 [[0]
 [1]]

Bra <0|:
 [[1 0]]

Bra <1|:
 [[0 1]]


In [6]:
# Inner Product
inner = bra1 @ ket1
print("⟨1|1⟩ =", inner)

⟨1|1⟩ = [[1]]


In [7]:
# Superposition State [∣ψ⟩=1/sqrt(2) (​∣0⟩+∣1⟩​)]
psi = (ket0 + ket1) / np.sqrt(2)
print("State |psi>:\n", psi)

norm = psi.conj().T @ psi
print("Normalization check:", norm)

State |psi>:
 [[0.707]
 [0.707]]
Normalization check: [[1.]]


In [8]:
# OPERATORS (Pauli Matrices)

sigma_x = np.array([[0,1],
                    [1,0]])

sigma_y = np.array([[0,-1j],
                    [1j,0]])

sigma_z = np.array([[1,0],
                    [0,-1]])

I2 = np.identity(2) #Identity Matrix
print("Identity Matrix (2x2):\n", I2, "\n")

print("Pauli X:\n", sigma_x, "\n")
print("Pauli Y:\n", sigma_y, "\n")
print("Pauli Z:\n", sigma_z, "\n")

Identity Matrix (2x2):
 [[1. 0.]
 [0. 1.]] 

Pauli X:
 [[0 1]
 [1 0]] 

Pauli Y:
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]] 

Pauli Z:
 [[ 1  0]
 [ 0 -1]] 



In [9]:
# Expectation Value (⟨A⟩=⟨ψ∣A∣ψ⟩)

exp_x = psi.conj().T @ sigma_x @ psi
# exp_y = psi.conj().T @ sigma_y @ psi
# exp_z = ket0.conj().T @ sigma_z @ ket0

print("<sigma_x> =", exp_x)

<sigma_x> = [[1.]]


In [10]:
# DENSITY MATRIX — PURE STATE {ρ=∣ψ⟩⟨ψ∣}

rho_pure = psi @ psi.conj().T
print("Density matrix (pure state):\n", rho_pure)

print("Trace:", np.trace(rho_pure))

purity = np.trace(rho_pure @ rho_pure)
print("Purity Tr(rho^2) =", purity)

Density matrix (pure state):
 [[0.5 0.5]
 [0.5 0.5]]
Trace: 0.9999999999999998
Purity Tr(rho^2) = 0.9999999999999996


In [11]:
# Mixed State [Suppose: |0⟩ with probability 0.5 and |1⟩ with probability 0.5]

rho_mixed = 0.5 * (ket0 @ ket0.conj().T) + \
            0.5 * (ket1 @ ket1.conj().T)

print("Mixed state density matrix:\n", rho_mixed)

print("Purity:", np.trace(rho_mixed @ rho_mixed))

Mixed state density matrix:
 [[0.5 0. ]
 [0.  0.5]]
Purity: 0.5


In [12]:
# Expectation Value (using Trace formula: ⟨A⟩=Tr(ρA))

exp_trace = np.trace(rho_pure @ sigma_z)
print("Expectation via trace:", exp_trace)

Expectation via trace: 0.0


In [13]:
# Unitary Evolution {ρ → UρU†}

H = (1/np.sqrt(2))*np.array([[1,1],
                             [1,-1]])

rho_evolved = H @ rho_pure @ H.conj().T

print("Evolved density matrix:\n", rho_evolved)

Evolved density matrix:
 [[1. 0.]
 [0. 0.]]


In [14]:
# Tensor product utility
def tensor(a,b):
    return np.kron(a,b)

bell = (tensor(ket0,ket0) + tensor(ket1,ket1))/np.sqrt(2) # Create Bell State

rho_bell = bell @ bell.conj().T

# Partial trace over second qubit
rho_A = np.zeros((2,2), dtype=complex)

for i in range(2):
    rho_A += rho_bell[i::2, i::2]

print("Reduced density matrix of subsystem A:\n", rho_A)
print("Purity of subsystem:", np.trace(rho_A @ rho_A))

Reduced density matrix of subsystem A:
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Purity of subsystem: (0.4999999999999998+0j)


In [18]:
# ===============================
# NUMERICAL MCQs
# ===============================

# ===============================
# MCQ 1: A qubit state is: ∣ψ⟩=​1/sqrt(5)​(2∣0⟩+∣1⟩). What is the probability of measuring |1⟩?
# ===============================

# The qubit state is |ψ⟩ = (1/sqrt(5))*(2|0⟩ + |1⟩)
# The probability of measuring |1⟩ is the square of the amplitude of |1⟩.
# The amplitude of |1⟩ in this state is 1/sqrt(5).
probability_of_1 = (1/np.sqrt(5))**2
print(f"The probability of measuring |1⟩ is: {probability_of_1}")

The probability of measuring |1⟩ is: 0.19999999999999998


In [20]:
# ===============================
# MCQ 2: For the mixed state: ρ=1/2 I, What is purity?
# ===============================

I_2 = np.identity(2)

# Define the mixed state rho
rho_mcq2 = 0.5 * I_2

# Calculate rho^2
rho_mcq2_squared = rho_mcq2 @ rho_mcq2

# Calculate the purity
purity_mcq2 = np.trace(rho_mcq2_squared)

print("Mixed state rho:", rho_mcq2)
print("Purity of the mixed state:", purity_mcq2)

Mixed state rho: [[0.5 0. ]
 [0.  0.5]]
Purity of the mixed state: 0.5


In [24]:
# ===============================
# MCQ 3: If ρ=∣0⟩⟨0∣, What is: Tr(ρσz​)?
# ===============================

# Define rho
rho_mcq3 = ket0 @ bra0

# Calculate the product rho * sigma_z
product_rho_sigma_z = rho_mcq3 @ sigma_z

# Calculate the trace of the product
trace_rho_sigma_z = np.trace(product_rho_sigma_z)

print("Density matrix rho (|0><0|):\n", rho_mcq3)
print("Pauli Z operator:\n", sigma_z)
print("Product (rho * sigma_z):\n", product_rho_sigma_z)
print("Tr(rho * sigma_z) =", trace_rho_sigma_z)

Density matrix rho (|0><0|):
 [[1 0]
 [0 0]]
Pauli Z operator:
 [[ 1  0]
 [ 0 -1]]
Product (rho * sigma_z):
 [[1 0]
 [0 0]]
Tr(rho * sigma_z) = 1


In [25]:
# ===============================
# MCQ 4: Given density matrix: ρ=(0.7 0 ,​0 0.3​), Is the state pure?
# ===============================

# Define the given density matrix
rho_mcq4 = np.array([[0.7, 0],
                     [0, 0.3]])

# Calculate rho^2
rho_mcq4_squared = rho_mcq4 @ rho_mcq4

# Calculate the purity Tr(rho^2)
purity_mcq4 = np.trace(rho_mcq4_squared)

print("Given density matrix rho:\n", rho_mcq4)
print("rho^2:\n", rho_mcq4_squared)
print("Purity Tr(rho^2) =", purity_mcq4)

if np.isclose(purity_mcq4, 1.0):
    print("The state is pure.")
else:
    print("The state is not pure (it is a mixed state).")

Given density matrix rho:
 [[0.7 0. ]
 [0.  0.3]]
rho^2:
 [[0.49 0.  ]
 [0.   0.09]]
Purity Tr(rho^2) = 0.58
The state is not pure (it is a mixed state).
